defaults:
  -
   scope:
     path: ""
   values:
     layout: "default"
     sidebar:
     - href: '/dta_rapid'
       title: 'Index'
     - href: 'forms'
       title: 'Forms'
     topnav:
     - href: '/dta_rapid'
       title: 'Introduction'
     - href: 'README'
       title: 'Readme.md'
